app/models/user.py
from datetime import datetime, timezone
from hashlib import md5
from time import time
from typing import Optional

import jwt
import sqlalchemy as sa
import sqlalchemy.orm as so
from flask import current_app
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from app import db, login
from app.models.mixins import TimestampMixin

followers = sa.Table(
    'followers',
    db.metadata,
    # follower_id ----> User.id (who follows)
    sa.Column('follower_id', sa.Integer, sa.ForeignKey('users.id'),
              primary_key=True),
    # followed_id ----> User.id (who is followed)
    sa.Column('followed_id', sa.Integer, sa.ForeignKey('users.id'),
              primary_key=True)
)


class User(TimestampMixin, UserMixin, db.Model):
    __tablename__ = 'users'

    id: so.Mapped[int] = so.mapped_column(primary_key=True)
    username: so.Mapped[str] = so.mapped_column(sa.String(64), index=True,
                                                unique=True)
    email: so.Mapped[str] = so.mapped_column(sa.String(120), index=True,
                                             unique=True)
    password_hash: so.Mapped[Optional[str]] = so.mapped_column(sa.String(256))

    posts: so.Mapped[list['Post']] = so.relationship(  # noqa: F821
        'Post', back_populates='author', lazy='dynamic')

    role: so.Mapped[str] = so.mapped_column(sa.String(20), default='user')

    about_me: so.Mapped[Optional[str]] = so.mapped_column(sa.String(140))

    last_seen: so.Mapped[Optional[datetime]] = so.mapped_column(
        sa.DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc)
    )

    # User.following = users I follow
    following: so.Mapped[set['User']] = so.relationship(
        secondary=followers,
        primaryjoin=(followers.c.follower_id == id),
        secondaryjoin=(followers.c.followed_id == id),
        collection_class=set,
        back_populates='followers'
    )

    # User.followers = users who follow ME
    followers: so.Mapped[set['User']] = so.relationship(
        secondary=followers,
        primaryjoin=(followers.c.followed_id == id),
        secondaryjoin=(followers.c.follower_id == id),
        collection_class=set,
        back_populates='following'
    )

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def avatar(self, size):
        digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return f'https://www.gravatar.com/avatar/{digest}?d=identicon&s={size}'

    @property
    def is_admin(self):
        return self.role == 'admin'

    def follow(self, user):
        self.following.add(user)

    def unfollow(self, user):
        self.following.discard(user)

    def is_following(self, user) -> bool:
        return user in self.following

    def followers_count(self) -> int:
        stmt = (
            sa.select(sa.func.count())
            .select_from(followers)
            .where(followers.c.followed_id == self.id)
        )
        return db.session.scalar(stmt)

    def following_count(self) -> int:
        stmt = (
            sa.select(sa.func.count())
            .select_from(followers)
            .where(followers.c.follower_id == self.id)
        )
        return db.session.scalar(stmt)

    def following_posts(self):
        Post = sa.orm.class_mapper(User).registry._class_registry['Post']

        following_ids = (
            sa.select(followers.c.followed_id)
            .where(followers.c.follower_id == self.id)
        )

        query = (
            sa.select(Post)
            .where(
                sa.or_(
                    Post.user_id.in_(following_ids),
                    Post.user_id == self.id,
                )
            )
            .order_by(Post.created_at.desc())
        )

        return query

    def get_reset_password_token(self, expires_in=600):
        return jwt.encode({
            'reset_password': self.id,
             'exp': time() + expires_in
            },
            current_app.config['SECRET_KEY'],
            algorithm='HS256'
        )

    @staticmethod
    def verify_reset_password_token(token):
        try:
            id = jwt.decode(
                token,
                current_app.config['SECRET_KEY'],
                algorithms=['HS256']
            )['reset_password']
            current_app.logger.debug('🔐👤 User succesfully identified')
        except Exception:
            current_app.logger.debug(
                '⚠️ Token invalid or expired. User not fount')
            return
        return db.session.get(User, id)

    # TODO:
    # mutual_friends() — mutual followers
    # suggested_follows() — subscription recommendations

    def __repr__(self):
        return '<User {}>'.format(self.username)


@login.user_loader
def load_user(id):
    return db.session.get(User, int(id))

app/routes.py
from datetime import datetime, timezone
from urllib.parse import urlsplit

import sqlalchemy as sa
from flask import (
    Blueprint,
    abort,
    current_app,
    flash,
    g,
    make_response,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from flask_babel import _
from flask_login import current_user, login_required, login_user, logout_user

from app import Config, db
from app.forms import (
    EditProfileForm,
    EmptyForm,
    # FollowForm,
    LoginForm,
    PostForm,
    RegistrationForm,
    ResetPasswordForm,
    ResetPasswordRequestForm,
    # UnfollowForm,
)
from app.models import Post, User
from app.utils.email import send_email, send_password_reset_email

main_bp = Blueprint('main', __name__)


@main_bp.route('/', methods=['GET', 'POST'])
@main_bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(body=form.post.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        current_app.logger.info(
            f'📝 New post created by {current_user.username}: '
            f'"{post.body[:30]}..."')
        flash(_('Your post is now live!'))
        return redirect(url_for('main.index'))

    page = request.args.get('page', 1, type=int)
    posts = db.paginate(current_user.following_posts(), page=page,
                        per_page=Config.POSTS_PER_PAGE, error_out=False)
    next_url = url_for('main.index', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.index', page=posts.prev_num) \
        if posts.has_prev else None
    return render_template(
        'pages/index.html', title='Home', form=form,
        posts=posts.items, next_url=next_url, prev_url=prev_url
    )


@main_bp.route('/explore')
@login_required
def explore():
    page = request.args.get('page', 1, type=int)
    query = sa.select(Post).order_by(Post.created_at.desc())
    posts = db.paginate(query, page=page,
                        per_page=Config.POSTS_PER_PAGE, error_out=False)
    next_url = url_for('main.explore', page=posts.next_num) \
        if posts.has_next else None
    prev_url = url_for('main.explore', page=posts.prev_num) \
        if posts.has_prev else None

    return render_template(
        'pages/index.html', title='Explore', posts=posts.items,
        next_url=next_url, prev_url=prev_url
    )


@main_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm()
    if form.validate_on_submit():
        user = db.session.scalar(
            sa.select(User).where(User.username == form.username.data))

        if user is None:
            current_app.logger.warning(
                f'❌ Login failed — unknown username "{form.username.data}"')
            flash(_('Invalid username or password'))
            return redirect(url_for('main.login'))

        if not user.check_password(form.password.data):
            current_app.logger.warning(
                f'🔐 Wrong password attempt for user "{form.username.data}"')
            flash(_('Invalid username or password'))
            return redirect(url_for('main.login'))

        login_user(user, remember=form.remember_me.data)
        current_app.logger.info(f'🔑 Logged in: {user.username}')

        next_page = request.args.get('next')
        if not next_page or urlsplit(next_page).netloc != '':
            next_page = url_for('main.index')
        return redirect(next_page)
    return render_template('pages/login.html', title='Sign In', form=form)


@main_bp.route('/logout')
def logout():
    username = current_user.username
    logout_user()
    current_app.logger.info(f'🚪 User logged out: {username}')
    return redirect(url_for('main.index'))


@main_bp.route('/reset_password_request', methods=['GET', 'POST'])
def reset_password_request():
    current_app.logger.debug(
        f'➡️ Enter reset_password_request ({request.method})')

    if current_user.is_authenticated:
        current_app.logger.debug(
            f'⚠️ User {current_user.username} is already authenticated. '
            f'Redirecting to index.')
        return redirect(url_for('main.index'))
    form = ResetPasswordRequestForm()
    if form.validate_on_submit():
        current_app.logger.debug(
            f'📩 Form submitted with email="{form.email.data}"')

        user = db.session.scalar(
            sa.select(User).where(User.email == form.email.data))
        if user:
            current_app.logger.debug(
                f'✅ User found: id={user.id}, username={user.username}. '
                f'Sending reset email...')
            send_password_reset_email(user)
        else:
            current_app.logger.debug(
                f'❌ No user with email "{form.email.data}"')

        flash(_('Check your email for the instructions to reset your password'))
        current_app.logger.debug(
            '➡️ Redirecting to login after request processing')
        return redirect(url_for('main.login'))

    current_app.logger.debug(
        '🖼 Rendering reset_password_request form')
    return render_template('pages/reset_password_request.html',
                           title='Reset Password', form=form)


@main_bp.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    current_app.logger.debug(
        f'➡️ Enter reset_password with token="{token[:25]}...". '
        f'Method: {request.method}')

    if current_user.is_authenticated:
        current_app.logger.debug(
            f'⚠️ User {current_user.username} is already authenticated. '
            f'Redirecting to index.')
        return redirect(url_for('main.index'))
    user = User.verify_reset_password_token(token)
    if not user:
        current_app.logger.debug(
            '❌ Invalid or expired token. Redirecting to index.')
        return redirect(url_for('main.index'))

    current_app.logger.debug(
        f'✅ Token valid. Resetting password for '
        f'user id={user.id}, username={user.username}')

    form = ResetPasswordForm()

    if form.validate_on_submit():
        current_app.logger.debug(
            f'🔐 Form submitted for password reset. '
            f'New password length={len(form.password.data)}')

        user.set_password(form.password.data)
        db.session.commit()

        current_app.logger.debug(
            f'💾 Password updated in DB for user id={user.id}')
        flash(_('Your password has been reset.'))
        current_app.logger.debug('➡️ Redirecting to login after success')
        return redirect(url_for('main.login'))

    current_app.logger.debug('🖼 Rendering password reset form')
    return render_template('pages/reset_password.html', form=form)
    return render_template('pages/index.html')


@main_bp.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        current_app.logger.info(
            f'👤 Already authenticated user tried to access /register: '
            f'{current_user}'
        )
        return redirect(url_for('main.index'))

    form = RegistrationForm()

    if form.validate_on_submit():
        current_app.logger.info(
            f'📝 Registration attempt: '
            f'username={form.username.data}, email={form.email.data}'
        )

        user = User(username=form.username.data, email=form.email.data)
        current_app.logger.debug(f'🧱 User object created: {user}')

        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()

        current_app.logger.info(
            f'🎉 New user registered successfully: {user.username}'
        )

        flash(_('Congratulations, you are now a registered user!'))
        return redirect(url_for('main.login'))

    return render_template('pages/register.html', title='Register', form=form)


@main_bp.route('/user/<username>')
@login_required
def user(username):
    current_app.logger.debug(
        f'👤 Current user accessing profile: {current_user}'
    )
    current_app.logger.info(
        f'🔎 Profile request for username="{username}"'
    )

    user = db.first_or_404(sa.select(User).where(User.username == username))

    page = request.args.get('page', 1, type=int)

    query = (
        sa.select(Post)
        .where(Post.user_id == user.id)
        .order_by(Post.created_at.desc())
    )

    posts = db.paginate(
        query, page=page, per_page=Config.POSTS_PER_PAGE, error_out=False
    )

    next_url = (
        url_for('user', username=user.username, page=posts.next_num)
        if posts.has_next else None
    )
    prev_url = (
        url_for('user', username=user.username, page=posts.prev_num)
        if posts.has_prev else None
    )

    form = EmptyForm()
    button_label = 'Unfollow' if current_user.is_following(user) else 'Follow'
    form.set_label(_(button_label))

    return render_template('pages/user.html', user=user, posts=posts.items,
                           next_url=next_url, prev_url=prev_url, form=form)


@main_bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.now(timezone.utc)
        db.session.commit()


@main_bp.route('/edit_profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    current_app.logger.debug(
        f'👤 Edit profile request by: {current_user}'
    )

    form = EditProfileForm(current_user.username)

    if form.validate_on_submit():
        current_app.logger.info(
            f'📝 Profile update submitted: username={form.username.data}'
        )

        current_user.username = form.username.data
        current_user.about_me = form.about_me.data
        db.session.commit()

        current_app.logger.info(
            f'✅ Profile updated successfully for user={current_user.username}'
        )

        flash(_('Your changes have been saved.'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if title %}
      <title>{{ title }} - Microblog</title>
    {% else %}
      <title>Welcome to Microblog</title>
    {% endif %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
          crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Microblog</a>
        <button class="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link"
                 aria-current="page"
                 href="{{ url_for('main.index') }}">{{ _("Home") }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link"
                 aria-current="page"
                 href="{{ url_for('main.explore') }}">{{ _("Explore") }}</a>
            </li>
          </ul>
          <ul class="navbar-nav mb-2 mb-lg-0">
            {% if current_user.is_anonymous %}
              <li class="nav-item">
                <a class="nav-link"
                   aria-current="page"
                   href="{{ url_for('main.login') }}">{{ _("Login") }}</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link"
                   aria-current="page"
                   href="{{ url_for('main.user', username=current_user.username) }}">{{ _("Profile") }}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link"
                   aria-current="page"
                   href="{{ url_for('main.logout') }}">{{ _("Logout") }}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container mt-3">
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          {% for message in messages %}<div class="alert alert-info" role="alert">{{ message }}</div>{% endfor %}
        {% endif %}
      {% endwith %}
      {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous">
    </script>
    {{ moment.include_moment() }}
  </body>
</html>

app/templates/bootstrap_wtf.html
{% macro form_field(field, autofocus) %}
  {%- if field.type == 'BooleanField' %}
    <div class="form-check mb-3">
      {{ field(class='form-check-input') }}
      {{ field.label(class='form-check-label') }}
    </div>
  {%- elif field.type == 'RadioField' %}
    {{ field.label(class='form-label') }}
    {%- for item in field %}
      <div class="form-check{% if loop.last %} mb-3{% endif %}">
        {{ item(class='form-check-input') }}
        {{ item.label(class='form-check-label') }}
      </div>
    {%- endfor %}
  {%- elif field.type == 'SelectField' %}
    {{ field.label(class='form-label') }}
    {{ field(class='form-select mb-3') }}
  {%- elif field.type == 'TextAreaField' %}
    <div class="mb-3">
      {{ field.label(class='form-label') }}
      {% if autofocus %}
        {{ field(class='form-control' + (' is-invalid' if field.errors else '') , autofocus=True) }}
      {% else %}
        {{ field(class='form-control' + (' is-invalid' if field.errors else '') ) }}
      {% endif %}
      {%- for error in field.errors %}<div class="invalid-feedback">{{ error }}</div>{%- endfor %}
    </div>
  {%- elif field.type == 'SubmitField' %}
    {{ field(class='btn btn-primary mb-3') }}
  {%- else %}
    <div class="mb-3">
      {{ field.label(class='form-label') }}
      {% if autofocus %}
        {{ field(class='form-control' + (' is-invalid' if field.errors else '') , autofocus=True) }}
      {% else %}
        {{ field(class='form-control' + (' is-invalid' if field.errors else '') ) }}
      {% endif %}
      {%- for error in field.errors %}<div class="invalid-feedback">{{ error }}</div>{%- endfor %}
    </div>
  {%- endif %}
{% endmacro %}
{% macro quick_form(form, action="", method="post", id="", novalidate=False) %}
  <form {%- if action != None %} action="{{ action }}"{% endif -%}
        {%- if method %}method="{{ method }}"{% endif %}
        {%- if id %} id="{{ id }}"{% endif -%}
        {%- if novalidate %} novalidate{% endif -%}>
    {{ form.hidden_tag() }}
    {%- for field, errors in form.errors.items() %}
      {%- if form[field].widget.input_type == 'hidden' %}
        {%- for error in errors %}<div class="invalid-feedback">{{ error }}</div>{%- endfor %}
      {%- endif %}
    {%- endfor %}
    {% set ns = namespace(first_field=true) %}
    {%- for field in form %}
      {% if field.widget.input_type != 'hidden' -%}
        {{ form_field(field, ns.first_field) }}
        {% set ns.first_field = false %}
      {%- endif %}
    {%- endfor %}
  </form>
{% endmacro %}

app/templates/index.html
{% extends "base.html" %}
{% block content %}
  <h1>Hi, {{ current_user.username }}!</h1>
  {% if form %}
    <form action="" method="post">
      {{ form.hidden_tag() }}
      <p>
        {{ form.post.label }}
        <br>
        {{ form.post(cols=32, rows=4) }}
        <br>
        {% for error in form.post.errors %}<span style="color: red;">[{{ error }}]</span>{% endfor %}
      </p>
      <p>{{ form.submit() }}</p>
    </form>
  {% endif %}
  {% for post in posts %}
    {% include '_post.html' %}
  {% endfor %}
  {% if prev_url %}<a href="{{ prev_url }}">Newer posts</a>{% endif %}
  {% if next_url %}<a href="{{ next_url }}">Older posts</a>{% endif %}
{% endblock %}

app/templates/user.html
{% extends "base.html" %}
{% block content %}
  <table>
    <tr valign="top">
      <td>
        <img src="{{ user.avatar(128) }}">
      </td>
      <td>
        <h1>User: {{ user.username }}</h1>
        {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
        {% if user.last_seen %}<p>Last seen on: {{ user.last_seen }}</p>{% endif %}
        <p>{{ user.followers_count() }} followers, {{ user.following_count() }} following.</p>
        {% if user == current_user %}
          <p>
            <a href="{{ url_for('main.edit_profile') }}">Edit your profile</a>
          </p>
        {% elif not current_user.is_following(user) %}
          <p>
            <form action="{{ url_for('main.follow', username=user.username) }}"
                  method="post">
              {{ form.hidden_tag() }}
              {{ form.submit(value='Follow') }}
            </form>
          </p>
        {% else %}
          <p>
            <form action="{{ url_for('main.unfollow', username=user.username) }}"
                  method="post">
              {{ form.hidden_tag() }}
              {{ form.submit(value='Unfollow') }}
            </form>
          </p>
        {% endif %}
      </td>
    </tr>
  </table>
  <hr>
  {% for post in posts %}
    {% include '_post.html' %}
  {% endfor %}
  {% if prev_url %}<a href="{{ prev_url }}">Newer posts</a>{% endif %}
  {% if next_url %}<a href="{{ next_url }}">Older posts</a>{% endif %}
{% endblock %}